@startuml Program
skinparam style strictuml
skinparam monochrome true


interface ASTNode {
    getLine(): int
    getColumn(): int
}

class Program {
    statements: List<Statement>
}

class Statement

class Expression

class Definition

class VarDef

class FuncDef

class Type

ASTNode <|.. Program
ASTNode <|-- Statement
ASTNode <|-- Expression
ASTNode <|-- Definition
Program o-- "0..n" Definition
Statement o.. Expression
Definition <|.. VarDef
Definition <|.. FuncDef
FuncDef o-- "0..n" Statement
FuncDef o-- "0..n" VarDef
VarDef o-- "1..n" Type

@enduml
