@startuml Statements
skinparam style strictuml
skinparam monochrome true


interface ASTNode {
    getLine(): int
    getColumn(): int
}

interface Statement

class If {
    condition: Expression
    ifBody: List<Statement>
    elseBody: List<Statement>
}

class Puts {
    expression: Expression
}

class In {
    expression: Expression
}

class While {
    expression: Expression
}

class Return {
    expression: Expression
}

class Assignement {
    expression: Expression
}

ASTNode <|-- Statement
Statement <|.. If
Statement <|.. In
Statement <|.. While
Statement <|.. Return
Statement <|.. Assignement

If o-- "1" Expression
Puts o-- "1" Expression
While o-- "1" Expression
In o-- "1" Expression
Return o-- "1" Expression
Assignement o-- "1" Expression
If o-- "0..n" Statement
While o-- "0..n" Statement


@enduml
