@startuml Statements
skinparam style strictuml
skinparam monochrome true


interface ASTNode {
    getLine(): int
    getColumn(): int
}

interface Statement

class Conditional {
    condition: Expression
    ifBody: List<Statement>
    elseBody: List<Statement>
}

class Puts {
    expression: Expression
}

class In {
    expression: Expression
}

class While {
    body: List<Statement>
    condition: Expression
}

class Return {
    expression: Expression
}

class Assignment {
    leftExp: Expression

}

ASTNode <|-- Statement
Statement <|.. Conditional
Statement <|.. In
Statement <|.. While
Statement <|.. Return
Statement <|.. Assignment
Statement <|.. Puts
Conditional o-- "0..n" Statement
While o-- "0..n" Statement


@enduml
