@startuml Statements
skinparam style strictuml
skinparam monochrome true


interface ASTNode {
    getLine(): int
    getColumn(): int
}

interface Statement

class If {
    condition: Expression
    ifBody: List<Statement>
    elseBody: List<Statement>
}

class Write {
    expression: Expression
}

ASTNode <|-- Statement
Statement <|.. If
Statement <|.. Write

If o-- "1" Expression
Write o-- "1" Expression
If o-- "0..n" Statement


@enduml
