@startuml Types
skinparam style strictuml
skinparam monochrome true

interface ASTNode {
    getLine(): int
    getColumn(): int
}

interface Type

class IntType

class RealType

class CharType

class ArrayType

class VoidType

class FunctionType

class StructType

ASTNode <|-- Type
Type <|.. IntType
Type <|.. RealType
Type <|.. CharType
Type <|.. ArrayType
Type <|.. VoidType
Type <|.. FunctionType
Type <|.. StructType

@enduml
